language: objective-c
osx_image: xcode9.2

install:
  - bundle install
  - bundle exec pod repo update --verbose
  - bundle exec pod install

script:
  - xcodebuild -workspace 'Allkdic.xcworkspace' -scheme 'Allkdic' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c
