targets:
  Testing:
    templates: [Framework]
    dependencies:
      - sdk: XCTest.framework
      - package: Nimble
      - package: Quick
      - package: Stubber

  TestingTests:
    templates: [UnitTest]
    templateAttributes:
      testTarget: Testing
