targets:
  Testing:
    templates: [Framework]
    dependencies:
      - sdk: XCTest.framework
      - carthage: Nimble
      - carthage: Quick

  TestingTests:
    templates: [UnitTest]
    templateAttributes:
      testTarget: Testing
